---
- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml 

  pre_tasks:
    - name: Run Pretasks
      include: pre-tasks/main.yml

  roles:
    - neovim
    - docker
    - rust
    - nodejs

