---
- name: Update and upgrade apt
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Required System Packages
  apt:
    pkg:
      - apt-transport-https
      - software-properties-common
      - ca-certificates
      - curl
    state: latest
    update_cache: true

- name: Nodejs Setup
  import_tasks: nodejs.yml

- name: Neovim Setup
  import_tasks: neovim.yml

- name: Docker Setup
  import_tasks: docker.yml
