---
- name: Update and upgrade apt
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Packages
  package:
    name:
      - apt-transport-https
      - software-properties-common
    state: present

- name: Nodejs Setup
  import_tasks: nodejs.yml

- name: Neovim Setup
  import_tasks: neovim.yml
