---
- name: Update and upgrade apt
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Required System Packages
  apt:
    pkg:
      - apt-transport-https
      - software-properties-common
      - ca-certificates
      - curl
    state: latest
    update_cache: true

- name: set distro codename when OS is Linux Mint
  ansible.builtin.set_fact:
    distro_codename: focal
  when: ansible_facts['distribution'] == 'Linux Mint'

    #- name: Add Ansible PPA
    # ansible.builtin.apt_repository:
    #repo: "ppa:ansible/ansible"
    #codename: "{{ distro_codename | default(omit) }}"

- name: Nodejs Setup
  tags: nodejs
  import_tasks: nodejs.yml

- name: Neovim Setup
  tags: nvim
  import_tasks: neovim.yml

- name: Docker Setup
  tags: docker
  import_tasks: docker.yml
