---

- name: Install Neovim
  get_url:
    url: 'https://github.com/neovim/neovim/releases/latest/download/nvim.appimage'
    dest: "/usr/bin"
    mode: 'u+x'

#- name: Install neovim
#  apt:
#    name: neovim
#    state: present

- name: use nvim for vi
  alternatives: name=vi path=/usr/bin/nvim.appimage

- name: use nvim for vim
  alternatives: name=vim path=/usr/bin/nvim.appimage

- name: use nvim for editor
  alternatives: name=editor path=/usr/bin/nvim.appimage

