---
- name: Create neovim config directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ nvim_config_home }}/after"
  - "{{ nvim_config_home }}/after/plugin"
  - "{{ nvim_config_home }}/lua"
  owner: "{{ regular_user }}"
  mode: 'u+x'

- name: Add lua config files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'init.lua', dest: '{{ nvim_config_home }}' }
    - { src: 'set.lua', dest: '{{ nvim_config_home }}/lua' }
    - { src: 'color.lua', dest: '{{ nvim_config_home }}/after/plugin' }
  owner: "{{ regular_user }}"
  mode: 'u+x'
