---
- name: Create neovim config directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "/home/{{ regular_user }}/.config/nvim"  
  - "/home/{{ regular_user }}/.config/nvim/after"
  - "/home/{{ regular_user }}/.config/nvim/after/plugin"
  - "/home/{{ regular_user }}/.config/nvim/lua/plugins"
